### ISSUE TITLE
vz: lima managed vm hangs with high CPU usage when computer wakes up from sleep. 

### ISSUE THREAD

**Issue by vsiravar** [lima-vm/lima#1609]
#### Problem
When the laptop wakes up from sleep, Virtualization Framework starts consuming 100%-220%(from Activity Monitor) CPU and is unresponsive. All limactl commands fail. The way around it is to recreate vm. 
Cannot ssh into the vm on the exposed port thereby preventing passing commands from host to vm. 
Related issue: https://github.com/docker/for-mac/issues/6655

####  Expected behaviour
That the vm should not hang when the computer wakes up from sleep. 

#### Host info
```
macOS version: 13.4
cpu brand: Apple M1 Pro
lima version: 0.16.0
```

**Comment by balajiv113** [comment]
@vsiravar 
is this consistently reproducible ?

Before sleep was there any high intensive task running in vm ?

**Comment by vsiravar** [comment]
> @vsiravar is this consistently reproducible ?

No, it's quite intermittent.
> Before sleep was there any high intensive task running in vm ?

Not really, I just have a hello-world container running in the vm. I have not experienced this behaviour with qemu.

**Comment by vsiravar** [comment]
> With current master we now have support for video display. If possible could you enable display and try to replicate the same ??

Sure, will try this out. Thanks!

**Comment by ningziwen** [comment]
I think this doesn't only happen when computer wakes up from sleep...

I successfully initialized the VM and ran some commands normally. But after I reply several messages in Slack and come back (around 10 mins), it starts to hang and return `FATA[0928] exit status 255`.

VM Service has 300% + CPU usage.


<img width="1283" alt="Screenshot 2023-06-08 at 3 33 14 PM" src="https://github.com/lima-vm/lima/assets/8747309/a45b2ccd-79af-4a6b-9f82-993b7968c181">

**Comment by balajiv113** [comment]
@ningziwen could you also try enabling display as mentioned above and see ??

Also do share you template which you used.

**Comment by ningziwen** [comment]
@balajiv113 Sorry I didn't get what it means. Would you like to do screen recording and upload the video? Or using any GUI? Could you point me the instruction if it is GUI?

**Comment by balajiv113** [comment]
@ningziwen 
Steps to enable display 

- Build and Install lima from master
- Edit your template with 
```
   video:
     display: "vz"
```
- Start your template 
- Do the normal work and try to reproduce the freeze.
- When hangs check if the display is usable / does contain any logs

This will give us a idea if there are some issues with network/whole vm itself.

**Comment by balajiv113** [comment]
I tired the above steps myself. Haven't got high cpu usage but the freeze happens.

On checking the GUI during the freeze even that was not responsive so i think the freeze happens on virtualization.framework level not on network. 

I have also raised a support ticket with Apple with the same info.

Note: This happens to me on M1 only. My intel runs smooth for weeks with sleep and wake cases

**Comment by ningziwen** [comment]
@balajiv113 Hey. Did you get any reply from Apple? Is the support ticket link sharable?

**Comment by vsiravar** [comment]
Updated ticket description and title based on new behaviour observed.

**Comment by ryancurrah** [comment]
Maybe once https://github.com/lima-vm/lima/issues/1659 is resolved you can look at the `serial.log` to see if there is any log messages.

**Comment by bsideup** [comment]
Confirming that this is still happening (`HEAD` as of today)

**Comment by outcoldman** [comment]
I am also experiencing the same issue. Just started using limactl instead of other VM providers. First had to deal with the time shift, so I have added the following 

```yaml
timedatectl set-ntp no
apt update
apt install -y ntp
```

Now, every morning get to the high CPU usage, and cannot access my VMs.

**Comment by kj-creater** [comment]
I started a lima virtual machine with the following command, and logged in to the virtual machine background from video using root

``` bash
limactl create --name=default template://docker \
--cpus=2 --memory=4 --vm-type=vz --mount-writable=true \
--disk=5 --network=lima:user-v2 --rosetta --video

limactl start
```
How can I confirm whether it is a problem with the virtual machine network or the m1 virtualization service?

I have encountered both of the following situations:

1. When I run `lima date -R` in the terminal to freeze, I can confirm from the video that the virtual machine is still running and the CPU usage is not high;
2. When I run `lima date -R` in the terminal to freeze, I can confirm from the video that the virtual machine has stopped and the `Virtualization` process takes up 200% of the CPU resources;

How can I help identify the problem in the above two situations?

lima version `0.18.0`
macOS version `14.0 (23A344)`

**Comment by kj-creater** [comment]
When I wrote the above the second scenario happened

1. There is no error message in the `ha.stderr.log` file
2. Virtualization process CPU usage is 200%
3. video frozen
<img width="1920" alt="image" src="https://github.com/lima-vm/lima/assets/118981282/85cc666f-972b-4fd8-90f0-81b2fdf9c7d9">

**Comment by terev** [comment]
@balajiv113 Was able to catch the following in the network log when this occurs:
```
tail ~/.colima/_lima/_networks/user-v2/usernet.user-v2.stderr.log
time="2023-11-12T08:00:45-05:00" level=info msg="new connection from  to "
2023/11/12 08:00:48 tcpproxy: for incoming conn 127.0.0.1:52125, error dialing "192.168.104.1:22": connect tcp 192.168.104.1:22: connection was refused
```
Unsure if this is relevant. The network process seems to remain alive.

**Comment by terev** [comment]
I also tried disabling rosetta but that did not help. Something interesting I noticed though is that after disabling rosetta, when the vm hangs, cpu is pinned at half the allocated cpu. Pinned at 100% when allocated 2 cpu.

**Comment by cdfmlr** [comment]
After upgrading my M2 Mac mini to Sonoma, I've been encountering this issue frequently. Yesterday, I noticed that one of my Lima VM and an UTM VM (both utilizing the virtualization.framework) froze simultaneously.

The UTM VM works after killing and restarting it. However, the Lima VM fails to restart after a `lima stop -f`. When I use `lima start`, that VM encounters errors similar to issue #1915 (by what I remember from, the logs are lost). Recreating the VM solves the problem.

In addition, my Colima VM, also running on vz, has been experiencing frequent hangs as well. I can always resolve it by using the `lima stop -f` command and then restarting it.

**Comment by terev** [comment]
I'm able to reproduce this issue almost every time when starting a large docker compose project (which I'm unable to share unfortunately). Today I noticed something new. I opened the system log utility to view any logs related to virtualization during one of these events. Doing so I was able to get some logs that seem interesting:

```
default	16:56:39.933077-0500	symptomsd	Received CPU usage trigger: 
  com.apple.Virtualization.Virtual[72861] () used 90.01s of CPU over 177.06 seconds (averaging 50%), violating a CPU usage limit of 90.00s over 180 seconds.
default	16:56:40.028006-0500	symptomsd	RESOURCE_NOTIFY trigger for com.apple.Virtualization.Virtual [72861] (90009971208 nanoseconds of CPU usage over 177.00s seconds, violating limit of 90000000000 nanoseconds of CPU usage over 180.00s seconds)
```

These logs occur very close to when the the vm begins to hang. From my naive perspective this kind of seems like the os may be killing the virtualization process for using too much cpu. Does that seem possible? I tried setting the vm's cpu limit to the number of cores my machine has but am still able to reproduce this.

**Comment by n-io** [comment]
> I tired the above steps myself. Haven't got high cpu usage but the freeze happens.
> 
> On checking the GUI during the freeze even that was not responsive so i think the freeze happens on virtualization.framework level not on network.
> 
> I have also raised a support ticket with Apple with the same info.
> 
> Note: This happens to me on M1 only. My intel runs smooth for weeks with sleep and wake cases

I have the same issue with qemu. Running the same command will sometimes work and sometimes freeze the vm, requiring a `stop --force`, with CPU usage being somewhere around 400%. However, the 400% CPU usage occur on the `qemu-system-x86_64` task. I'm on an M2 Mac and am using `cpuType:\ x86_64: "max"` in my config, using qemu v8.2.1.

You have already raised a ticket with Apple, but would it be possible to double-check and confirm if in your scenario the behaviour is reproducible using qemu instead of vz?

**Comment by noncrab** [comment]
I've seen similar on macOS–I'd created a VM wit the default settings and 8GB of ram, and the bits I was running inside of it consumed all of the available RAM. The machines don't have swap enabled by default, so presumably it's busy trying to reclaim RAM, and failing. In these cases, `lima stop -f` doesn't do much, as it seemingly requires access to ssh into the machine (from what i can see if I force terminate the VM process via activity monitor). 

So as I see it, there's a few layers of issues here:

* The default VM image (ubuntu, I think?) seems to prefer wedging itself over killing processes to handle low memory situations
* There's no swap configured by default (this might be arguable, really)
* `lima stop -f` relies on the machine being up and acessible in order to terminate it.

I'm going to see if a reboot allows me to recover the machine to be recovered 🤞 (edit: restarting the machine does reset lima's understanding of the machine's state. Maybe there's a daemon somewhere I can try killling instead…)
