### ISSUE TITLE
⚠️ QEMU (homebrew) is broken on Intel: `[hostagent] Driver stopped due to error: "signal: abort trap"` (or `"exit status 255"`) ... `QEMU has already exited`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1742]
**Update (Aug 27, 2023)**: The issue is solved again in `8.1.0-1` (https://github.com/Homebrew/brew/pull/15903 , https://github.com/Homebrew/homebrew-core/pull/140596). Run `brew reinstall -f --force-bottle qemu` to install the updated v8.1.0 bottle.

**Update (Aug 23, 2023)**: This seems to be broken again in v8.1.0  😞 (https://github.com/Homebrew/homebrew-core/issues/140244) . See the `Workarounds` below.

**Update (Aug 14, 2023)**: The issue is now solved in https://github.com/Homebrew/homebrew-core/pull/139492 . 
Run `brew reinstall -f --force-bottle qemu` to install the updated v8.0.4 bottle.

- - -
Homebrew bottle of QEMU v8.0.4 (Intel) ~is~ was broken due to a signing issue: https://github.com/Homebrew/homebrew-core/pull/139409
```console
$ limactl start
...
[hostagent] Driver stopped due to error: "signal: abort trap" 
...
[hostagent] QEMU has already exited
...

$ qemu-system-x86_64 -accel hvf
qemu-system-x86_64: -accel hvf: Unknown Error
Abort trap: 6

$ codesign --verify /usr/local/Cellar/qemu/8.0.4/bin/qemu-system-x86_64 
/usr/local/Cellar/qemu/8.0.4/bin/qemu-system-x86_64: invalid signature (code or signature have been modified)
In architecture: x86_64
```
(The error message can be also `[hostagent] Driver stopped due to error: "exit status 255"`)

### Option 1: Downgrade QEMU to v8.0.3

```bash
brew uninstall qemu
curl -OSL https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb
brew install ./qemu.rb
```

### Option 2: Install QEMU from the source

```bash
brew uninstall qemu
brew install --build-from-source qemu
```

### Option 3: Sign the QEMU binary locally
Lima v0.17.2 shows a prompt to suggest applying this workaround.

```bash
cat >entitlements.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.hypervisor</key>
    <true/>
</dict>
</plist>
EOF

codesign --sign - --entitlements entitlements.xml --force /usr/local/bin/qemu-system-$(uname -m | sed -e s/arm64/aarch64/)
```

- - -

Thanks to  @z0sen for reporting this in https://github.com/abiosoft/colima/issues/777

**Comment by afbjorklund** [comment]
Lima project probably needs to have an optional QEMU installation tarball (in a different project, like alpine-lima).

**Comment by AkihiroSuda** [comment]
The issue is now solved:
- https://github.com/Homebrew/homebrew-core/pull/139492

**Comment by benmoss** [comment]
Still seeing this when I run `colima start` after running `brew reinstall -f --force-bottle qemu`:

> time="2023-08-16T11:22:47-04:00" level=warning msg="QEMU binary \"/Users/mossity/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" is not properly signed with the \"com.apple.security.hypervisor\" entitlement" error="binary \"/Users/mossity/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" seems signed but lacking the \"com.apple.security.hypervisor\" entitlement"
time="2023-08-16T11:22:47-04:00" level=warning msg="You have to sign the QEMU binary with the \"com.apple.security.hypervisor\" entitlement manually. See https://github.com/lima-vm/lima/issues/1742 ."

**Comment by AkihiroSuda** [comment]
@benmoss 

- ARM Mac or Intel Mac?
- Does `limactl start` (not `colima start`) print the same warning? If `limactl start` does not print a warning, it is an issue of colima.
- Output of  `codesign --display --entitlements - --xml /opt/homebrew/Cellar/qemu/8.0.4/bin/qemu-system-x86_64 ` ? (qemu binary path might be different)

**Comment by benmoss** [comment]
- I'm on ARM
- `limactl start` doesn't print any warning, says "QEMU binary "/opt/homebrew/bin/qemu-system-aarch64" seems properly signed with the "com.apple.security.hypervisor" entitlement
- `codesign --display ...` shows that it has the hypervisor entitlement

So it looks like it is a colima problem. Feel free to ignore!

**Comment by AkihiroSuda** [comment]
The binary seems broken again with the 8.1.0 bottle 😞 
- https://github.com/Homebrew/homebrew-core/pull/140237

**Comment by afbjorklund** [comment]
Besides the bloat, this seems like another good reason to not use Homebrew for the QEMU installation.

**Comment by AkihiroSuda** [comment]
I guess we should also rush to make `vz` default?
`vz` also had a different incompatibility issue though (https://github.com/lima-vm/lima/issues/1577).

**Comment by afbjorklund** [comment]
Adding a check for the entitlement to the brew formula would probably also be a good idea, to stop re-re-regressions from happening again in the future

**Comment by AkihiroSuda** [comment]
> Adding a check for the entitlement to the brew formula would probably also be a good idea, to stop re-re-regressions from happening again in the future

Already done in Lima v0.17.2: 
- https://github.com/lima-vm/lima/pull/1743

(The `Y/n` prompt defaults to `n` when `--tty=false` though)

**Comment by AkihiroSuda** [comment]
The issue is solved again in `8.1.0-1` (https://github.com/Homebrew/brew/pull/15903 , https://github.com/Homebrew/homebrew-core/pull/140596).

Run `brew reinstall -f --force-bottle qemu` to install the updated v8.1.0 bottle.

**Comment by AkihiroSuda** [comment]
@janvda Using Lima without Colima may work as a workaround:
`limactl start template://docker`

Removing `~/.colima/_wrapper` may work too.

**Comment by remidebette** [comment]
Hi,
I just noticed today after coming back from holidays that Colima is broken.
I am on a macbook pro M1. I have applied the same steps as @janvda to no avail.

This issue should be reopened

**Comment by AkihiroSuda** [comment]
> I am on a macbook pro M1

You are hitting something different (maybe https://gitlab.com/qemu-project/qemu/-/issues/1864 ), as the OP is about Intel.

**Comment by janvda** [comment]
> have applied the same steps as @janvda to no avail.

FYI The following workaround worked for me on my macbook pro with intel processors:
* https://github.com/abiosoft/colima/issues/792#issuecomment-1703314392

**Comment by connorblack** [comment]
@edw-eqix Beautiful - this is the current workaround until the maintainers get this sorted

**Comment by RicardoMonteiroSimoes** [comment]
I've just tried it now on my M1 mac, and this is the current output with the most recent `brew install --HEAD qemu`:

```
> "QEMU binary \"/Users/risi/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" is not properly signed with the \"com.apple.security.hypervisor\" entitlement" error="binary \"/Users/risi/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" seems signed but lacking the \"com.apple.security.hypervisor\" entitlement"
> You have to sign the QEMU binary with the "com.apple.security.hypervisor" entitlement manually. See https://github.com/lima-vm/lima/issues/1742 .
```

**Comment by RicardoMonteiroSimoes** [comment]
Thanks for the response, my bad, was on the wrong repo :)

**Comment by msankhala** [comment]
> From my slightly-cleaned-up-for-display error below, something seems to be checking whether the wrapper itself is signed.

After signing the actual binary with the following command:

```sh
codesign --sign - --entitlements entitlements.xml --force /usr/local/bin/qemu-system-$(uname -m | sed -e s/arm64/aarch64/)
```

I also signed the wrapper with something like:

```sh
codesign --sign - --entitlements entitlements.xml --force ~/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64
```
and it worked. Now It shows me message like this:

```sh
INFO[0010] starting ...                                  context=vm
> Using the existing instance "colima"
> QEMU binary "/Users/mutant/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64" seems properly signed with the "com.apple.security.hypervisor" entitlement
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/mutant/.lima/colima/serial*.log")
> SSH Local Port: 60997
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"

```

**Comment by DinoChiesa** [comment]
As above, [This hint (Option 3, local signing)](https://github.com/lima-vm/lima/issues/1742#issue-1848287754), worked for me. Intel Mac, Sonoma 14.1.
